config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'static_pages#welcome'
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :rewards
  resources :games
  resources :tasks
  resources :contests do
    get 'participate', on: :member
    member do
      get :get_tasks
    end
  end

  get 'activate_diploma' => 'rewards#activate_diploma'
  post 'get_activate_diploma' => 'rewards#get_activate_diploma'
  
  get 'honors' => 'static_pages#honors'
  get 'sites' => 'static_pages#sites'
  get 'instruction' => 'static_pages#instruction'
  get 'contacts' => 'static_pages#contacts'
  get 'logout' => 'sessions#destroy'
  get 'signin' => 'sessions#new'
  get 'signup' => 'users#new'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def welcome
		@contests = Contest.all
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/contacts.html.erb
<div class='slide contest-show'>
	<div class='contest-content tac'>
		<h1>Наша электронная почта:</h1>
		<h1>pokori-olimp@yandex.ru</h1>
	</div>
	<!--<h1 style='margin: 100px;'>
		<b><span>Д</span>
		<span>И</span>
		<span>П</span>
		<span>Л</span>
		<span>О</span>
		<span>М</span></b>
	</h1> -->
</div>

app/views/static_pages/honors.html.erb
<div class='slide'>
	<div class='central-content all-honor-content tac'>
	<h1 class='mtm mbs'>Награды</h1>
	<% (1..10).each do |val| %>
		<img src='/diploma_samples/<%=val%>.jpg' />
	<% end %>
	</div>
</div>

app/views/static_pages/instruction.html.erb
<div class='slide block680 ma mtl instruction'>
	<!--<img class='contest-background-img' src='http://www.goldrhapsody.com/wp-content/uploads/2015/09/bigstock-Honey-and-Herbal-tea-on-wooden-67103101.jpg' /> -->
	<div>
		<h1 class='tac mbm'>Как принять участие?</h1>

		<p>1. Выберите олимпиаду</p>

		<p>2. Выберите класс</p>

		<p>3. Выполните олимпиадные задания</p>

		<p>4. После прохождения олимпиады введите Ваши данные без ошибок и выберите диплом</p>

		<p>5. Зайдите в раздел «Итоги» и получите заслуженную награду 
		(Дипломы на электронную почту администрация сайта не присылает, вы скачиваете диплом самостоятельно в разделе «Итоги»)</p>
	</div>
	
</div>

app/views/static_pages/sites.html.erb
<div class='slide our-site'>
	<div class='card ma'>
		<div class='col golden_section38'>
			<img src='/images/beecan.gif' />
		</div>
		<div class='col golden_section62'>
			<h1><a href='http://joy-olympic.ru' target='_blank'>www.joy-olympic.ru</a></h1>
			<div class='description'>
			Яркие и анимированные иллюстрации на сайте подарят детям не только знания, но и улыбки. Принимайте учатие!</br></br>
		📚 <b>Предметы</b>: математика, окружающий мир, русский и английский языки.
			</div>
		</div>
		<div class='clear'></div>
	</div>
</div>
<div class='slide our-site'>
	<div class='card ma'>
		<div class='col golden_section38'>
			<img src='/images/sprint.gif' />
		</div>
		<div class='col golden_section62'>
			<h1><a href='http://sprint-olympic.ru' target='_blank'>www.sprint-olympic.ru</a></h1>
			<div class='description'>
				Предметные олимпиады для школьников 1-11 классов. Все понятно и доступно!</br></br>
			📚 <b>Предметы</b>: математика, окружающий мир, русский и английский языки, информатика и ИКТ, история.
			</div>
		</div>
		<div class='clear'></div>
	</div>
</div>

app/views/static_pages/welcome.html.erb
<div class='slide welcome-home'>
	<img id="image-main-page" src="/images/homa.jpg" alt='покори олимп | дистанционные олимпиады по школьным предметам' data-pin-nopin="true">
	<div class="slide-content" id="slide-content1">
		<img src='/images/logo-name11.png' alt='покори олимп | дистанционные олимпиады для школьников' class='logoname'/>
		<h1>Дистанционные олимпиады 2019</h1>
		<h2>Олимпиады по школьным предметам</br>Бесплатное участие и мгновенный результат</h2>
		<!--<div class='activities'>
			<a class='btn btn-our btn-our-green'>Зарегист!</a>
			<a class='btn btn-our btn-our-blue'>Попробовать бесплатно</a>
		</div>-->
  </div>
</div>
<div class='olympics-home mbl'>
	  <h1 class='tac title-on-page'>Наши олимпиады</h1>
	  <% @contests.each do |contest|  %>
		  <%= link_to contest_path(contest) do %>
				<div class='col col-press-25'>
					<div class='card'>
						<img src='<%=contest.image%>' alt='Олимпиады по математике, информатике, русскому и английскому языкам'/>
						<h4><%=contest.title%></h4>
					</div>
				</div>
			<% end %>
		<% end %>
		<!--<div class='col col-33p game-olympics'>
			<img src='/images/game-olympics.gif' />
			<h4>Обучающие игры</h4>
		</div>-->
		<div class='clearboth'></div>
</div>
<div class='slide others-our-sites-on-welcome'>
	<img src='/images/pointing-right.png'>&nbsp; <%= link_to 'Другие наши сайты с олимпиадами', sites_path %> &nbsp;<img src='/images/pointing-left.png'>
</div>