config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'static_pages#welcome'
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :rewards
  resources :games
  resources :tasks
  resources :contests do
    get 'participate', on: :member
    member do
      get :get_tasks
    end
  end

  get 'activate_diploma' => 'rewards#activate_diploma'
  post 'get_activate_diploma' => 'rewards#get_activate_diploma'
  
  get 'honors' => 'static_pages#honors'
  get 'sites' => 'static_pages#sites'
  get 'instruction' => 'static_pages#instruction'
  get 'contacts' => 'static_pages#contacts'
  get 'logout' => 'sessions#destroy'
  get 'signin' => 'sessions#new'
  get 'signup' => 'users#new'

end

app/models/reward.rb
class Reward < ActiveRecord::Base
  belongs_to :contest
  belongs_to :user

  def diploma_number1(position, prize, diploma_number)
    dnum = rand(100)
    image = MiniMagick::Image.open("./public/original_diplomas/#{diploma_number}.jpg")

    subject = ""
    if self.contest_id == 1
      subject = "по русскому языку"
    elsif self.contest_id == 2
      subject = "по математике"
    elsif self.contest_id == 3
      subject = "по окружающему миру"
    elsif self.contest_id == 4
      subject = "по литературе"
    elsif self.contest_id == 5
      subject = "по биологии"
    elsif self.contest_id == 6
      subject = "по географии"
    elsif self.contest_id == 7
      subject = "по истории"
    elsif self.contest_id == 8
      subject = "по ОБЖ"
    elsif self.contest_id == 9
      subject = "по английскому языку"
    end

    institution = self.institution
    margin_text = -80
    if institution.size > 44
      institution_44 = institution[0, 44]
      index_inst = institution_44.rindex(" ")
      fp_institution = institution[0, index_inst]
      sp_institution = institution[index_inst+1, institution.size]
      margin_text = 0
    end

    image.resize "1654x2339"
    image.format "jpg"
    image.combine_options do |c|
      c.gravity 'NorthWest'
      c.fill '#383838'
      c.pointsize '102'
      c.draw "text 505,700 '#{prize}'"

      c.fill '#383838'
      c.pointsize '52'
      c.draw "text 505,#{position} 'Награждается'"
      c.pointsize '82'
      c.draw "text 505,#{position+90} '#{self.name}'"
      c.pointsize '43'
      c.draw "text 505,#{position+240} '#{self.age}'"
      c.pointsize '43'
      if institution.size > 44
        c.draw "text 505,#{position+320} '#{fp_institution}'"
        c.draw "text 505,#{position+400} '#{sp_institution}'"
      else
        c.draw "text 505,#{position+320} '#{institution}'"
      end
      c.pointsize '43'
      if self.prize != 0
        c.draw "text 505,#{position+480+margin_text} 'за победу во Всероссийской олимпиаде'"
      else
        c.draw "text 505,#{position+480+margin_text} 'за участие во Всероссийской олимпиаде'"
      end
      c.pointsize '43'
      c.draw "text 505,#{position+560+margin_text} '#{subject}'"
      c.pointsize '30'
      c.draw "text 767,1650 '#{Russian::strftime(self.created_at, "%d.%m.%Y г.")}'"
      c.pointsize '26'
      if diploma_number == 10
        c.fill '#ffffff'
      end
      c.draw "text 840,2260 '№ П-#{self.id}'"
    end
    output_diploma = "./public/diplomas/diploma#{dnum}.jpg"
    image.write output_diploma
    return "/diplomas/diploma#{dnum}.jpg"
  end
end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
  before_action :find_reward, except: [:index, :new, :create, :activate_diploma, :get_activate_diploma]
  before_action :require_admin, only: [:activate_diploma]

  def index
    @rewards = Reward.order(created_at: "DESC").limit(1500)
  end

  def show
    if @reward.paid
      case @reward.prize
      when 0
         prize = 'Участника'
      when 1
         prize = 'I степени'
      when 2
         prize = 'II степени'
      when 3
         prize = 'III степени'
      end
      
      @output_diploma = @reward.diploma_number1(920, prize, @reward.number)
    end
  end

  def create
    if logged_in?
      @reward = current_user.rewards.create reward_params
    else
      @reward = Reward.create reward_params
    end
    render nothing: true
  end

  def activate_diploma
    @reward = Reward.new
  end
  def get_activate_diploma
    @reward = Reward.find(params[:reward][:id])
    if @reward.update(paid: true)
      flash[:success] = 'Отлично!'
    else
      flash[:error] = "Провал"
    end
    redirect_to activate_diploma_path
  end

  private
    def reward_params
      params.require(:reward).permit(
        :name, :age, :institution, :prize, :score, :contest_id, :number)
    end

    def find_reward
      @reward = Reward.find(params[:id])
    end
end

app/helpers/reward_helper.rb
module RewardHelper
end

app/views/rewards/activate_diploma.html.erb
<div class='slide contest-show'>
	<div class='contest-content tac'>
		<h2 class='h--thin mbm'><span class='prxs'>Активация диплома</span></h2>
		<%= simple_form_for(@reward, url: get_activate_diploma_path) do |f| %>
				<%= f.input :id, label: false, input_html: { class: 'input-sp',  placeholder: 'id диплома' } %>
		    <%= f.button :submit, 'Активировать диплом', class: 'btn btn-our btn-our-green mtl' %>
		<% end %>
	</div>
</div>

app/views/rewards/index.html.erb
<div class='slide block980 ma mtl rewards'>
	<div class='tac'>
		<h1>Итоги</h1>
		<p>Найдите свою фамилию, после этого скачайте диплом.</p>
		<table>
			<tbody>
				<tr class='tac'>
			    <th width='5%'>№</th>
			    <th width='15%'>Дата</th>
			    <th width='60%'>Участник</th>
			    <th width='20%'>Степень</th>
			   </tr>
				<% @rewards.each do |reward|  %>
					<% 
						if reward.prize == 0
							prize = "Участник"
						else
							prize = reward.prize.to_s + " степень"
						end 
					%>
					<tr>
						<td width='5%'>
							<%= reward.id %>
						</td>
						<td width='15%'>
							<%= Russian::strftime(reward.created_at, "%d %B %Y") %>
						</td>
						<td width='60%'>
							<b><%= link_to reward.name, reward_path(reward) %></b>
						</td>
						<td width='20%'>
							<%= prize %>
						</td>
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>

app/views/rewards/show.html.erb
<% 
	if @reward.prize == 0
		prize = "Участник"
	else
		prize = @reward.prize.to_s + " место"
	end 
%>
<% if @reward.contest_id == 1
      subject = "по русскому языку"
    elsif @reward.contest_id == 2
      subject = "по математике"
    elsif @reward.contest_id == 3
      subject = "по окружающему миру"
    elsif @reward.contest_id == 4
      subject = "по литературе"
    end %>
<div class='slide slide-reward'>
	<% if !@reward.paid %>
		<div class='pinpen'></div>
		<div class='reward-data'>
			<img src='/diploma_samples/<%=@reward.number%>.jpg' />
			<div class='participant'>
				<h1><%= prize %></h1>
				<h2><%= @reward.name %></h2>
				<h3><%= subject %></h3>
			</div>
			<div class='clearboth'></div>
		</div>
		<h4 class='mbm'>Диплом станет доступен для скачивания в течение 12 часов после оплаты</h4>
		<a id='buy-diploma' class='btn btn-our btn-our-green'>Приобрести этот диплом за 100 рублей</a>
		<div class='payment-form'>
			<form action='https://money.yandex.ru/eshop.xml' method='post'>
					<input required name='shopId' value='50046' type='hidden'/>
					<input required name='scid' value='34157' type='hidden'/>
					<input required name='sum' value='100' type='hidden'><br>
					<input required name='customerNumber' value='<%=@reward.id%>' size='64' type='hidden'/><br>
								
					<label>Ваш Email:</label><br>	
					<input class='custEmail' name='custEmail' value='' size='64' type='text'/><br><br>
					
					<label>Ваше ФИО:</label><br>
					<input class='custName' name='custName' value='' size='64' type='text'/><br>

					
					<input class='ym_merchant_receipt' name='ym_merchant_receipt' value='{\"customerContact\":
\"onlineyageniy@yandex.ru\",\"taxSystem\": 2, \"items\": [{\"quantity\": 1,\"price\": {\"amount\": 100.00},\"tax\": 1,\"text\": \"Услуги по обработке данных\", \"paymentMethodType\": \"full_prepayment\", \"paymentSubjectType\": \"payment\"}]}' type="hidden"/>
					<br>
					<input id='getpay' class='btn btn-our btn-our-green' type='submit' value='Оплатить' disabled='disabled'>	
			</form>
		</div>
	<% else %>
		<div class='col-3of6 ma mtl img-diploma'>
			<h1><%= prize %></h1>
			<img src='<%= @output_diploma %>' width='100%' />
		</div>
	<% end %>
</div>