config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'static_pages#welcome'
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :rewards
  resources :games
  resources :tasks
  resources :contests do
    get 'participate', on: :member
    member do
      get :get_tasks
    end
  end

  get 'activate_diploma' => 'rewards#activate_diploma'
  post 'get_activate_diploma' => 'rewards#get_activate_diploma'
  
  get 'honors' => 'static_pages#honors'
  get 'sites' => 'static_pages#sites'
  get 'instruction' => 'static_pages#instruction'
  get 'contacts' => 'static_pages#contacts'
  get 'logout' => 'sessions#destroy'
  get 'signin' => 'sessions#new'
  get 'signup' => 'users#new'

end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  
  has_many :rewards

  before_save { self.email = email.downcase }

  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { message: '', with: VALID_EMAIL_REGEX, },
                    uniqueness: true
  validates :password,
    length:       { message: 'Не менее 6 символов', minimum: 6 },
    presence:     { message: 'Не может быть пустым' },
    confirmation: { message: 'Пароли не совпадают' },
    on:           :create

  validates :password,
    confirmation: { message: 'Пароли не совпадают' },
    on:           :update
end

app/models/user/sign_in.rb
class User::SignIn < ActiveType::Object
  attribute :email, :string
  attribute :password, :string

  validates :email, presence: true
  validates :password, presence: true

  def set_error
    errors.add(:email, 'Неверные данные')
    errors.add(:password, ' ')
  end
end

app/controllers/users_controller.rb
class UsersController < InheritedResources::Base

	def index
		@users=User.all
	end

	def new
		@user = User.new
	end

	def create
    @user = User.new user_params
    if @user.save
      auto_login @user
      flash[:success] = "Добро пожаловать! Читайте дневники других педагогов, черпайте материал и вдохновение!"
      redirect_to root_path
    else
      render 'new'
    end
  end

	def edit
	end
	def update
	end

	def destroy
	end

  private
    def user_params
      params.require(:user).permit(:email, :name, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class='slide slide-new-user'>
	<div class='hidden-xs pinbee'></div>
	<div class='wrap-form-advantages'>
		<h3>Спасибо, что нашли время зарегистрировать аккаунт для Вашего ребенка!</h3>
		<div class='wrapper'>
			<div class='reg-form'>
					<h4>Регистрация</h4>
					<%= simple_form_for(@user, url: users_path, html: { class: 'registration-form' }) do |f| %>
				      <%= f.input :name, label: false, input_html: { class: 'input-sp', placeholder: 'Имя' } %>
				      <%= f.input :email, label: false, input_html: { class: 'input-sp',  placeholder: 'Электронный адрес' } %>
				      <%= f.input :password, label: false, input_html: { class: 'input-sp',  placeholder: 'Пароль' } %>
				      <%= f.input :password_confirmation, label: false,  input_html: { class: 'input-sp',  placeholder: 'Повторите пароль' } %>
				      <%= f.button :submit, 'Зарегистрироваться', class: 'btn btn-our btn-our-green' %>
				  <% end %>
					<p>У Вас уже есть профиль? Тогда войдите.</p>
			</div>
			<div class='advantages'>
				<h3><span>Зачем регистрироваться?</span></h3>
				<div class='advantages-list'>
					<div class='advantage'>
						<img src = '/images/free.png'/><span>Бесплатные дипломы</span>
					</div>	
					<div class='advantage'>
						<img src = '/images/teddy_bear.png'/><span>Виртуальный персонаж</span>
					</div>
					<div class='advantage'>
						<img src = '/images/sunsmile.png'/><span>Улыбка на лице Вашего ребенка</span>
					</div>
					<div class='advantage'>
						<img src = '/images/writedown.png'/><span>Книга знаний</span>
					</div>
					<div class='clearboth'></div>
				</div>
				<!--<img src='/images/creatures.png'  data-pin-nopin="true"/>-->
			</div>
			<div class='clearboth'></div>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class='standart-page'>
	<div class='menu-header'>
			<a>Задания</a>
			<a>Награды</a>
			<a>Достижения</a>
			<a>Еще что-нибудь</a>
	</div>
	<div class='main-content'>
		<div class='right-bar'>
		</div>
		<div class='content'>
			<h3>Задания на сегодня</h3>
		</div>
		<div class='clearboth'>
		</div>
	</div>
</div>
<div style = 'display: none;'><%= link_to logout_path, data: { no_turbolink: true } do %>
  Выход
<% end %></div>


<!--<div class='profile-info'>
			<img src='https://d13yacurqjgara.cloudfront.net/users/398490/screenshots/2722077/taco-preloader.gif' class='avatar'/>
			<div class='data-action'>
				<h2><%= @user.name %></h2>
				<div>
					<a>Награды (12)</a> | 
					<a>Достижения</a> |
					<a>Настройки</a>
				</div>
				<div class='wrap-honey'>
					Баночек меда: <img src='/images/honey.png' class='honey-img'/> <span>14</span>
				</div>
			</div>
		</div> -->