config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'static_pages#welcome'
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :rewards
  resources :games
  resources :tasks
  resources :contests do
    get 'participate', on: :member
    member do
      get :get_tasks
    end
  end

  get 'activate_diploma' => 'rewards#activate_diploma'
  post 'get_activate_diploma' => 'rewards#get_activate_diploma'
  
  get 'honors' => 'static_pages#honors'
  get 'sites' => 'static_pages#sites'
  get 'instruction' => 'static_pages#instruction'
  get 'contacts' => 'static_pages#contacts'
  get 'logout' => 'sessions#destroy'
  get 'signin' => 'sessions#new'
  get 'signup' => 'users#new'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Дистанционные олимпиады для школьников 2017 | Покори Олимп</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
  <meta name="description" content="Всероссийские дистанционные олимпиады по математике, русскому и английскому языкам. Результат сразу после участия!"/>
  <meta name="keywords" content="дистанционные олимпиады, всероссийские дистанционные олимпиады, дистанционная олимпиада по математике, дистанционная олимпиада по русскому языку, дистанционная олимпиада по английскому языку, дистанционные олимпиады для школьников, интернет олимпиады"/>

  <meta property="vk:title" content="Дистанционные олимпиады для школьников 2017 | Покори Олимп" />
  <meta property="vk:description" content="Всероссийские дистанционные олимпиады по математике, русскому и английскому языкам. Результат сразу после участия!" />
  <meta property="vk:url" content="http://pokori-olimp.ru" />
  <meta property="vk:image" content="http://pokori-olimp.ru/images/logo-text1.png" />
  <meta property="vk:type" content="website"/>

  <meta name="yandex-verification" content="44097bc71d796749" />

  <%= render "partials/metrika" unless current_user.try(:admin?) %>
  <script src='https://cdnjs.cloudflare.com/ajax/libs/buzz/1.2.0/buzz.min.js'></script>
  <link rel="stylesheet" href="http://webfonts.ru/import/arimo.css" type="text/css" media="screen" />
  <link href="http://allfont.ru/css/?fonts=open-sans" rel="stylesheet" type="text/css" />
  <link href="http://allfont.ru/css/?fonts=pt-sans" rel="stylesheet" type="text/css" />
  <link href="http://webfonts.ru/import/barkentina.css" rel="stylesheet" type="text/css" />
  <link href="http://webfonts.ru/import/arnamuserif.css" rel="stylesheet" type="text/css" />
  <link href="http://webfonts.ru/import/gentium.css" rel="stylesheet" type="text/css" />
  <link href="http://webfonts.ru/import/linlibslanted.css" rel="stylesheet" type="text/css" />
  <link href="http://webfonts.ru/import/merriweather.css" rel="stylesheet" type="text/css" />
  <link href="http://webfonts.ru/import/notoserif.css" rel="stylesheet" type="text/css" />
</head>
<body class=''>

    <div id="site-hat">
        <%= link_to root_path do %>
          <img class="hidden-xs" src="/images/logo-text1.png" alt='Дистанционные олимпиады для школьников' id="logo">
        <% end %>
        <nav>
          <%= link_to 'Главная', root_path %>
          <%= link_to 'Итоги', rewards_path %>
          <%= link_to 'Награды', honors_path %>
          <%= link_to 'Как принять участие?', instruction_path %>
        </nav>
    </div>

    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "alert alert-#{key}") %>
    <% end %>

    <div class='container'>
      <div class='wrap-content'>
        <%= yield %>
      </div>
    </div>

    <div class="footer">
      <div class="tac mtl">
        <hr>
        <p>
          <a href='https://vk.com/club57636029' target='_blank'><img src='/images/vk.png' width='30'/></a>
          <a class='mlm' href='https://ok.ru/group/52963370008673' target='_blank'><img src='/images/ok.png' width='30'/></a>
        </p>
        <p>
          <a href="rule.docx" class="privLink">Положение о проведение Всероссийских олимпиад</a> <a href="/contacts">Контакты</a> <a href="/oferta_p.docx">Договор-оферта</a>
          <br>
        </p>
        <p>
          <a href="soglasie_na_obrabotku_Pokori.docx" class="privLink">Согласие на обработку персональных данных</a> <a href="politika_Pokori.docx">Политика обработки персональных данных</a>
          <br>
        </p>
        <p>Организатор: <a href='http://ya-geniy.ru'>Я гений</a> (СМИ)</p>
      </div>
    </div>
</body>
</html>